### ISSUE TITLE
Disable PAM on macOS

### ISSUE THREAD

**Issue by adiroiban** [chevah/compat#677]
We get these errors on macOS

pam should be completly disabled and we should not support OS accounts on macOS

```
Traceback (most recent call last):
  File "/Users/runner/work/1/s/build-server/lib/python2.7/site-packages/chevah/compat/testing/nose_test_timer.py", line 89, in __call__
    self.__target()
  File "/Users/runner/work/1/s/build-server/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/runner/work/1/s/build-server/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/runner/work/1/s/build-server/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/runner/work/1/s/chevah/server/tests/normal/authentication/test_os.py", line 37, in <module>
    system_users._getPAMAuthenticate()
  File "/Users/runner/work/1/s/build-server/lib/python2.7/site-packages/chevah/compat/unix_users.py", line 416, in _getPAMAuthenticate
    from pam import authenticate as pam_authenticate
  File "/Users/runner/work/1/s/build-server/lib/python2.7/site-packages/pam.py", line 83, in <module>
    LIBPAM = load_library('pam', ['libpam.so', 'libpam.so.0', 'libpam.so.1'])
  File "/Users/runner/work/1/s/build-server/lib/python2.7/site-packages/pam.py", line 46, in load_library
    raise AssertionError("Failed to load '%s' library." % (nickname))
AssertionError: Failed to load 'pam' library.

```

**Comment by adiroiban** [comment]
will be fixed as part of #678
